//
//  ObjectListRouter.swift
//  challenge
//
//  Created by Michael Steudter on 12.07.22.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// swiftlint:disable identifier_name
@objc protocol ObjectListRoutingLogic {
	func routeToCreateObject() async
	func routeToEditObject(id: String) async
	func routeToAddRelationToObject(id: String, to objectId: String) async
}

class ObjectListRouter: NSObject, ObjectListRoutingLogic {

	weak var viewController: ObjectListViewController?

	@MainActor
	func routeToCreateObject() async {
		let createEditVc = CreateAndEditObjectViewController()
		createEditVc.interactor?.createObject()
		viewController?.navigationController?.pushViewController(createEditVc, animated: true)
	}

	@MainActor
	func routeToEditObject(id: String) async {
		let createEditVc = CreateAndEditObjectViewController()
		await createEditVc.interactor?.fetchObjectForEditing(request: .init(id: id))
		viewController?.navigationController?.pushViewController(createEditVc, animated: true)
	}

	@MainActor
	func routeToAddRelationToObject(id: String, to objectId: String) async {
		// TODO: Improve this. This might be error prone as it depends on the navigation stack.
		viewController?.navigationController?.popViewController(animated: true)
	}
}
