//
//  ObjectListRouter.swift
//  challenge
//
//  Created by Michael Steudter on 12.07.22.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// swiftlint:disable identifier_name
/// Possible routes from object list.
@objc protocol ObjectListRoutingLogic {
	/// Routes to object creation screen.
	func routeToCreateObject() async
	/// Routes to object editing screen.
	/// - Parameter id: The id of the object to edit.
	func routeToEditObject(id: String) async
}

final class ObjectListRouter: NSObject, ObjectListRoutingLogic {

	/// The source view controller.
	weak var viewController: ObjectListViewController?

	// MARK: - ObjectListRoutingLogic

	@MainActor
	func routeToCreateObject() async {
		let createEditVc = CreateAndEditObjectViewController()
		createEditVc.interactor?.createObject()
		viewController?.navigationController?.pushViewController(createEditVc, animated: true)
	}

	@MainActor
	func routeToEditObject(id: String) async {
		let createEditVc = CreateAndEditObjectViewController()
		await createEditVc.interactor?.fetchObjectForEditing(request: .init(id: id))
		viewController?.navigationController?.pushViewController(createEditVc, animated: true)
	}
}
