//
//  CreateAndEditObjectPresenter.swift
//  Challenge
//
//  Created by skrr on 12.07.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateAndEditObjectPresentationLogic {
	func presentObjectEditing(response: CreateAndEditObject.FetchObject.Response)
	func presentObjectCreating(response: CreateAndEditObject.CreateObject.Response)
}

class CreateAndEditObjectPresenter: CreateAndEditObjectPresentationLogic {
  weak var viewController: CreateAndEditObjectDisplayLogic?

  // MARK: Present

	func presentObjectEditing(response: CreateAndEditObject.FetchObject.Response) {
		let object = CreateAndEditObject.FetchObject.ViewModel.DisplayedObject(type: response.object.type,
																				name: response.object.name,
																			   description: response.object.description,
																			   relations: response.object.relations)
		let viewModel = CreateAndEditObject.FetchObject.ViewModel(object: object, relations: [])
		Task {
			await viewController?.displayObject(viewModel: viewModel)
		}
	}

	func presentObjectCreating(response: CreateAndEditObject.CreateObject.Response) {
		viewController?.createObject(viewModel: .init())
	}
}
