//
//  CreateAndEditObjectRouter.swift
//  Challenge
//
//  Created by skrr on 12.07.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateAndEditObjectRoutingLogic {
	func routeToObjectList()
	func routeToRelationsSelector(for id: String) async
}

protocol CreateAndEditObjectDataPassing {
	var dataStore: CreateAndEditObjectDataStore? { get }
}

class CreateAndEditObjectRouter: NSObject, CreateAndEditObjectRoutingLogic, CreateAndEditObjectDataPassing {

	weak var viewController: CreateAndEditObjectViewController?
	var dataStore: CreateAndEditObjectDataStore?

	func routeToObjectList() {
		viewController?.navigationController?.popViewController(animated: true)
	}

	@MainActor
	func routeToRelationsSelector(for id: String) async {
		let relationSelector = ObjectListViewController()
		var interactor = relationSelector.interactor
		interactor?.selectedObjectId = id
		await interactor?.listObjectSelector()
		await viewController?.navigationController?.pushViewController(relationSelector, animated: true)
	}
}
