//
//  CreateAndEditObjectRouter.swift
//  Challenge
//
//  Created by Michael Steudter on 12.07.22.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// swiftlint:disable identifier_name
/// Possible routes from CREATE and EDIT screen.
@objc protocol CreateAndEditObjectRoutingLogic {
	/// Route back to object list.
	func routeToObjectList()
	/// Route to object relations selection screen.
	func routeToRelationsSelector(for id: String) async
}

final class CreateAndEditObjectRouter: NSObject, CreateAndEditObjectRoutingLogic {

	/// The source view controller.
	weak var viewController: CreateAndEditObjectViewController?

	func routeToObjectList() {
		viewController?.navigationController?.popViewController(animated: true)
	}

	@MainActor
	func routeToRelationsSelector(for id: String) async {
		let relationSelector = ObjectListViewController()
		var interactor = relationSelector.interactor
		interactor?.selectedObjectId = id
		await interactor?.listObjectSelector()
		viewController?.navigationController?.pushViewController(relationSelector, animated: true)
	}
}
