//
//  CreateAndEditObjectModels.swift
//  Challenge
//
//  Created by skrr on 12.07.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
// swiftlint:disable nesting
enum CreateAndEditObject {
	// MARK: Use cases

	enum FetchObject {
		struct Request {
			var id: String
		}
		struct Response {
			var object: Object
		}
		struct ViewModel {
			let title = "Edit Object"
			struct DisplayedObject {
				var type: String
				var name: String
				var description: String
				var relations: Set<String>
			}
			var object: DisplayedObject
			var relations: [DisplayedObject]
		}
	}

	enum CreateObject {
		struct Request {
			var type: String
			var name: String
			var description: String
			var relations: Set<String>
		}
		struct Response {
			var object: Object
		}
		struct ViewModel {
			let title = "Create Object"
		}
	}

	enum UpdateObject {
		struct Request {
			var type: String
			var name: String
			var description: String
			var id: String
			var relations: Set<String>
		}
		struct Response {
			var object: Object
		}
		struct ViewModel { }
	}
}
