//
//  CreateAndEditObjectPresenter.swift
//  Challenge
//
//  Created by Michael Steudter on 12.07.22.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@MainActor
/// Protocol for presenting CREATE and EDIT screen.
protocol CreateAndEditObjectPresentationLogic {
	/// Presents screen for editing a fetched object.
	func presentObjectEditing(response: CreateAndEditObject.FetchObject.Response)
	/// Presents screen for creating a new object.
	func presentObjectCreating(response: CreateAndEditObject.CreateObject.Response)
}

final class CreateAndEditObjectPresenter: CreateAndEditObjectPresentationLogic {
  weak var viewController: CreateAndEditObjectDisplayLogic?

  // MARK: Present

	func presentObjectEditing(response: CreateAndEditObject.FetchObject.Response) {
		let object = CreateAndEditObject.FetchObject.ViewModel.DisplayedObject(type: response.object.type,
																				name: response.object.name,
																			   description: response.object.description,
																			   relations: response.object.relations,
																			   id: response.object.id)
		let viewModel = CreateAndEditObject.FetchObject.ViewModel(object: object, relations: [])
		Task {
			await viewController?.displayObject(viewModel: viewModel)
		}
	}

	func presentObjectCreating(response: CreateAndEditObject.CreateObject.Response) {
		Task {
			await viewController?.createObject(viewModel: .init())
		}
	}
}
